NETWORK=full
RO_BINDS=/usr /lib /lib64 /bin /sbin /etc/alternatives /etc/resolv.conf /etc/ssl /etc/ca-certificates /etc/passwd /etc/group
RW_BINDS=
EXTRA_RO_BINDS=
DEV_BINDS=
EXTRA_RW_BINDS=
TMPFS_MOUNTS=
ENV_SET=
ENV_UNSET=
